# Site settings
title: Alexandre Constantino's blog
#subtitle: Blogging the final frontier. These are the voyages of the starship Enterprise.
email: dreaming.about.electric.sheep@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Documenting some of my experiences with software and technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  alexconst

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [autolink, footnotes, with_toc_data]
highlighter: pygments

permalink: /:year/:month/:day/:title/

